openapi: 3.0.0
info:
  title: Swing Notes API
  version: 1.0.0
  description: API för att hantera anteckningar med inloggning och CRUD-funktionalitet.
servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /api/user/signup:
    post:
      summary: Skapa ett nytt användarkonto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Användare skapad
        "400":
          description: Felaktig data
        "500":
          description: Serverfel

  /api/user/login:
    post:
      summary: Logga in en användare
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Inloggning lyckades
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  message:
                    type: string
        "401":
          description: Ogiltiga uppgifter
        "500":
          description: Serverfel

  /api/notes:
    post:
      summary: Skapa en ny anteckning
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
      responses:
        "201":
          description: Anteckning skapad
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  text:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                  modifiedAt:
                    type: string
                    format: date-time
        "400":
          description: Felaktig data
        "500":
          description: Serverfel
    get:
      summary: Hämta alla anteckningar
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Anteckningar hämtade
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    text:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
                    modifiedAt:
                      type: string
                      format: date-time

  /api/notes/{id}:
    put:
      summary: Uppdatera en anteckning
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID för anteckningen
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
      responses:
        "200":
          description: Anteckning uppdaterad
        "400":
          description: Felaktig data
        "404":
          description: Anteckning ej hittad
        "500":
          description: Serverfel
    delete:
      summary: Ta bort en anteckning
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID för anteckningen
          schema:
            type: string
      responses:
        "200":
          description: Anteckning borttagen
        "404":
          description: Anteckning ej hittad
        "500":
          description: Serverfel

  /api/notes/search:
    get:
      summary: Söka bland anteckningar
      security:
        - bearerAuth: []
      parameters:
        - name: title
          in: query
          required: true
          description: Titel på anteckningen att söka efter
          schema:
            type: string
      responses:
        "200":
          description: Anteckningar som matchar sökningen
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    text:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
                    modifiedAt:
                      type: string
                      format: date-time
        "500":
          description: Serverfel
